article: https://www.bigclown.com/doc/projects/radio-lcd-thermostat/
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/174-1_project-thermostat-lcd-a-4.jpg?5de56e1c
articles:
  - title: Heating Control with HARDWARIO IoT Kit Thermostat
    url: https://www.hackster.io/165274/heating-control-with-hardwario-iot-kit-thermostat-4ec1fc
    description: Control your heating with this simple device that is easy to modify. You can control your sunblinds or boiler for optimal temperature.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/1050363/_WHbVUJ03Oa.blob?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: BigClown LCD Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
